### ISSUE TITLE
Savestates Do Not Work

### ISSUE THREAD

**Issue by nfox18212** [OceanRamen/Brainstorm#10]
Title says it all.  I have the latest release of Lovely and Brainstorm, and loaded up a seeded game of Balatro.  I hit Z+1-5 and X+1-5, and nothing happened.  The lovely console did not show any changes either.  No save states were created or loaded.  I've attached the lovely log to this issue.

I'm running this on Fedora 40 through Proton Experimental.  
[lovely-2024.10.15-12.14.35.log](https://github.com/user-attachments/files/17381667/lovely-2024.10.15-12.14.35.log)

**Comment by OceanRamen** [comment]
Hi nfox18212, 
Due to Brainstorms use in official "filtered" records, I made the decision to remove save-states from the latest version. To compensate for this loss, I will be releasing a separate save-manager mod, but that is currently in the works, and development has been slow due to a busy schedule. 
In the meantime, to continue using Brainstorm with save-states, you must download a previous release. 
Many thanks!
